routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('website.login');
});
Route::get('/qrcode', function () {
    return view('welcome');
});
Route::get('/login','Website\LoginController@index' )->name('website.login');
Route::middleware('auth')->group( function (){
    Route::get('/dashboard',[ App\Http\Controllers\Admin\DashboardController::class , 'index'] )->name('dashboard');
    Route::get('/acc/logout', [ App\Http\Controllers\Admin\Auth\LoginController::class , 'logout'])->name('logout');
    Route::group([
        'as' => 'admin.',
        'prefix' => 'admin',
        'middleware' => 'is_admin'
    ], function (){
        Route::resource('/product',Admin\ProductController::class);
        Route::delete('/product-deletemulti',[\App\Http\Controllers\Admin\ProductController::class,'deleteMulti'])->name('product.deletemuti');
        Route::get('/product-search',[\App\Http\Controllers\Admin\ProductController::class,'searchProduct'])->name('product.search');
        Route::resource('/user', Admin\UserController::class);
        Route::post('/updateus-ajax', [\App\Http\Controllers\Admin\UserController::class, 'updateAjax'])->name('user.update.ajax');
        Route::get('/task',[ App\Http\Controllers\Admin\TaskController::class , 'index'] )->name('list-task');
        Route::get('/add-task',[ App\Http\Controllers\Admin\TaskController::class , 'addTask'] )->name('addtask');
        Route::get('/edit-task/{idtask}',[ App\Http\Controllers\Admin\TaskController::class , 'editTask'] )->name('edittask');
    });
}
);

Route::get('/admin/login',[\App\Http\Controllers\Admin\Auth\LoginController::class, 'index'] )->name('admin.login');
Route::post('/admin/login',[\App\Http\Controllers\Admin\Auth\LoginController::class, 'login'])->name('admin.login');
Route::get('/admin/register-user', [\App\Http\Controllers\Admin\Auth\RegisterController::class, 'index'] )->name('admin.user.register');
Route::post('/admin/register-user', [\App\Http\Controllers\Admin\Auth\RegisterController::class, 'register'] )->name('admin.user.register');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $table = 'users';
    public function role(){
        return $this->belongsTo(Role::class, 'is_role', 'id');
    }
    public function product(){
        return $this->hasMany(Product::class, 'is_user', 'id');
    }
    public function task(){
        return $this->hasMany(Task::class, 'is_user', 'id');
    }
    public static function getUser()
    {
        return [
            'name' => 'Nguyễn Văn Hải',
            'email' => 'Vanhai@gmail',
            'phone' => '123'
        ];
    }
    public static function addUser($request)
    {

        $users = new User;
        $users -> name = $request -> nameuser;
        $users -> email = $request -> emailuser;
        $users -> password = bcrypt($request -> password);
        $users -> created_at = now();
        $users -> is_role = 3;
        return $users -> save();
    }
    public static function editUser($request,$id){
        $users = User::find($id);
        $users -> name = $request -> nameuser;
        $users -> email = $request -> emailuser;
        $users -> updated_at = now();
        return $users -> save();
    }
    public static function deleteUser($id){
        $user = User::find($id);
        $user -> delete();
    }
//    protected $fillable = [
//        'name',
//        'email',
//        'password',
//    ];
    protected $guarded = [];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $listUser = User::orderBy('id', 'DESC')->paginate(10);
//        dd($listUser);
        $data['listUser'] = $listUser;
        return view('admin.pages.user.users',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create',User::class);
        return view('admin.pages.user.adduser');
    }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', User::class);
        User::addUser($request);
        $request -> session() -> regenerate();
        return redirect()->route('admin.user.index')->with( ['addsuccses' => 1] );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $this->authorize('update', $user);
        $data['user'] = $user;
        return view('admin.pages.user.edituser',$data);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $this->authorize('update', $user);
        User::editUser($request,$id);
        $request -> session() -> regenerate();
        return redirect()->route('admin.user.index')->with( ['editsuccses' => 1] );

    }

    public function updateAjax(Request $request){
        $id = $request->idus;
        return User::editUser($request,$id);
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $user = User::find($request->id);
        $this->authorize('update', $user);
        User::deleteUser($request->id);
    }
}

resources/views/admin/pages/user/adduser.blade.php
@extends('admin.layouts.main',['title' => 'Add New User'])
@section('content')
    <div class="container">
        <div class="card card-default my-2">
            <div class="card-header">
                <h3 class="card-title">Add New User</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form action="{{ route('admin.user.store') }}" method="post">
                @csrf
                <div class="card-body">
                    <div class="error-content">
                        <ul>
                            @if ($errors -> any())
                                {{--                    {{ dd($errors) }}--}}
                                @foreach($errors->all() as $key => $value)
                                    <li class="text-danger">{{ $value }}</li>
                                @endforeach
                            @endif
                        </ul>
                    </div>
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <div class="form-group">
                        <label for="nameuser">Name</label>
                        <input type="text" class="form-control" name="nameuser" id="nameuser" placeholder="Enter Name" value="{{ old('nameuser') }}">
                    </div>
                    <div class="form-group">
                        <label for="emailuser">Email address</label>
                        <input type="text" class="form-control" id="emailuser" name="emailuser" value="{{ old('emailuser') }}" placeholder="Enter Email">
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                        </div>
                        <div class="form-group col-sm-6">
                            <label for="password_confirmation">Repeat Password</label>
                            <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Repeat Password">
                        </div>
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">

                    <a href="{{ route('admin.user.index') }}" class="btn btn-danger">Cancel</a>
                    <button type="submit"  class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/pages/user/edituser.blade.php
@extends('admin.layouts.main',['title' => 'Edit User'])
@section('content')
    <div class="container">
        <div class="card card-default my-2">
            <div class="card-header">
                <h3 class="card-title">Edit User <small>{{ $user->name }}</small></h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form action="{{ route('admin.user.update', $user->id)  }}" method="post">
                {{ method_field('PUT') }}}
                <div class="card-body">
                    <div class="error-content">
                        <ul>
                            @if ($errors -> any())
                                @foreach($errors->all() as $key => $value)
                                    <li class="text-danger">{{ $value }}</li>
                                @endforeach
                            @endif
                        </ul>
                    </div>
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <div class="form-group">
                        <label for="nameuser">Name</label>
                        <input type="text" class="form-control" name="nameuser" id="nameuser" placeholder="Enter Name" value="{{ $user->name }}">
                    </div>
                    <div class="form-group">
                        <label for="emailuser">Email address</label>
                        <input type="text" class="form-control" id="emailuser" name="emailuser" value="{{ $user->email }}" placeholder="Enter Email">
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">

                    <a href="{{ route('admin.user.index') }}" class="btn btn-danger">Cancel</a>
                    <button type="submit"  class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>

@endsection
@push('custom-scripts')
    <script type="text/javascript">
{{--        @if ( Session::get('editsuccses') == -1)--}}
{{--            console.log("fail");--}}
{{--            toastr.options.timeOut = 3000; // How long the toast will display without user interaction--}}
{{--        toastr.options.extendedTimeOut = 3000; // How long the toast will display after a user hovers over it--}}
{{--        toastr.error("Edit new Product is Fail","Fail");--}}
{{--        @endif--}}
    </script>

@endpush

resources/views/admin/pages/user/users.blade.php
@extends('admin.layouts.main',['title' => 'Users'])
@section('content')
    <div class="container">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Dashboard</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Users</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">List of Users</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="option-data">
                    <div class="my-2 left-option">
                        <input id="checkedAll" type="checkbox">
                        <buttom id="mutipDelete" class="btn btn-danger mx-1"><i class="fas fa-trash-alt"></i> Delete</buttom>
                        <a href="{{ route('admin.user.index') }}" class="btn btn-primary mx-1"><i class="fas fa-sync"></i> Refresh</a>
                        @can('create', \App\Models\User::class)
                        <a href="{{ route('admin.user.create') }}" class="btn btn-success mx-1"><i class="fas fa-user-plus"></i></a>
                        @endcan
                    </div>
                    <div class="right-option">
                        <form action="simple-results.html">
                            <div class="input-group text-center">
                                <label class="form-control form-control-md " for="filterby">Filter by: </label>
                                <select class="form-control form-control-md" id="filterby" name="filterby" id="filterby">
                                    <option value="1">ID</option>
                                    <option value="2">Name</option>\
                                    <option value="3">Email</option>
                                </select>
                                <input type="search" class="form-control form-control-md" placeholder="Search">
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-md btn-primary">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>

                    </div>

                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th style="width: 10px">ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Create At</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($listUser as $key => $value)
                        <tr id="row_{{ $value -> id  }}">
                            <td><input  type="checkbox" value="{{ $value -> id  }}" name="checkitems[]" id="check-item"></td>
                            <td>{{ $value -> id  }}</td>
                            <td>{{ $value -> name }}</td>
                            <td>{{ $value -> email }}</td>
                            <td>{{ $value -> created_at }}</td>
                            <td class="text-center">
                                <div>
                                    @can('update', $value)
                                    <a title="Edit" class="text-info" href="{{ route('admin.user.edit', $value -> id ) }}"><i class="far fa-edit"></i></a>

                                    <a title="Delete" class="text-danger" onclick="deleteUser({{ $value -> id }})" data-toggle="modal" data-target="#modal-default"><i class="fas fa-trash-alt"></i></a>
                                        <a title="Edit" class="text-info edituser" onclick="updateAdmin({{ $value -> id }})" id="button_{{ $value -> id }}" data-toggle="modal" data-target="#myModalUpdate">Ajax</a>
                                    @endcan
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <div class="number-pages">
                {{ $listUser->links('vendor.pagination.custom') }}
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal-default">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Confirm Delete User</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                </div>
                <div class="modal-body">
                    <p>Are you sure to delete User</p>
                    <input type="hidden" id="idUser">
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button onclick="apceptDelete()" type="button" class="btn btn-danger" data-dismiss="modal">Delete</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <div class="modal fade" id="myModalUpdate">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Confirm Delete User</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                </div>
                <div class="modal-body">
                    <form method="post" id="formUd" enctype="multipart/form-data" class="form-horizontal">
                        <div class="row form-group my-1">
                            <div class="col  col-md-3 "><label for="id-ud" class=" form-control-label">ID</label></div>
                            <div class="col-12 col-md-9"><input type="text" id="id-ud" name="id-ud" readonly class="form-control"></div>
                        </div>
                        <div class="row form-group my-1">
                            <div class="col  col-md-3 "><label for="fullname-ud" class=" form-control-label">Full name</label></div>
                            <div class="col-12 col-md-9"><input type="text" id="fullname-ud" name="fullname-ud" placeholder="Enter full name" class="form-control"><small class="text-danger" id="fullnameNN"></small></div>
                        </div>
                        <div class="row form-group my-1">
                            <div class="col  col-md-3"><label for="username-ud" class=" form-control-label">Email</label></div>
                            <div class="col-12 col-md-9"><input type="text" id="username-ud" name="email-ud" placeholder="Enter Email" class="form-control"><small class="text-danger" id="usernameNN"></small></div>
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <button onclick="saveUpdate()" type="button" class="btn btn-primary" data-dismiss="modal">Save</button>
                            <!-- <input href="" type="submit" class="btn btn-primary" id="bt-save-ud" name="bt-save-ud" value="Lưu"> -->
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
@push('custom-scripts')
    <script type="text/javascript">
        $( document ).ready(function() {
            // $('.edituser').click(function (e){
            //     console.log($(this).parent().find('td:nth-child(3)').text());
            // });

            @if ( Session::get('addsuccses') == 1)
                toastr.options.timeOut = 3000; // How long the toast will display without user interaction
                toastr.options.extendedTimeOut = 3000; // How long the toast will display after a user hovers over it
                toastr.info("Add new user is success","Success");
            @endif
            @if ( Session::get('editsuccses') == 1)
                toastr.options.timeOut = 3000; // How long the toast will display without user interaction
                toastr.options.extendedTimeOut = 3000; // How long the toast will display after a user hovers over it
                toastr.info("AEdit user is success","Success");
            @endif
        });

        function updateAdmin(id){
            var formud = $('#formUd');
            formud.find('input[name="id-ud"]').val(id);
            formud.find('input[name="fullname-ud"]').val($('#row_'+id+' td:nth-child(3)').text());
            formud.find('input[name="email-ud"]').val($('#row_'+id+' td:nth-child(4)').text());
        }
        function saveUpdate(){
            var formud = $('#formUd');
            let idus = formud.find('input[name="id-ud"]').val();
            let fullname = formud.find('input[name="fullname-ud"]').val();
            let email = formud.find('input[name="email-ud"]').val();
            $.ajax({
                url: '{{ route('admin.user.update.ajax') }}',
                method: 'POST',
                data: {
                    idus: idus,
                    nameuser: fullname,
                    emailuser: email,
                    _token: '{{csrf_token()}}'
                },
                success: function(result) {
                    console.log(result);
                    if ( result == 1 ){
                        $('#row_'+idus+' td:nth-child(3)').text(fullname);
                        $('#row_'+idus+' td:nth-child(4)').text(email);
                        toastr.options.timeOut = 3000; // How long the toast will display without user interaction
                        toastr.options.extendedTimeOut = 3000; // How long the toast will display after a user hovers over it
                        toastr.info("Update user is success","Success");
                        // $("#row_" + id).remove();
                    }
                }
            });
        }
        function deleteUser(id)
        {
            $("#idUser").val(id);
        }
        function apceptDelete(){
            let id = $("#idUser").val();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                type: 'DELETE',
                url: "user/"+id,
                data: { id: id , _token: '{{csrf_token()}}'},
                success:function(data){
                    // alert(data);
                    toastr.options.timeOut = 3000; // How long the toast will display without user interaction
                    toastr.options.extendedTimeOut = 3000; // How long the toast will display after a user hovers over it
                    toastr.info("Delete user is success","Success");
                    $("#row_" + id).remove();
                }
            });


        }
    </script>
@endpush
@endsection