routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('website.login');
});
Route::get('/qrcode', function () {
    return view('welcome');
});
Route::get('/login','Website\LoginController@index' )->name('website.login');
Route::middleware('auth')->group( function (){
    Route::get('/dashboard',[ App\Http\Controllers\Admin\DashboardController::class , 'index'] )->name('dashboard');
    Route::get('/acc/logout', [ App\Http\Controllers\Admin\Auth\LoginController::class , 'logout'])->name('logout');
    Route::group([
        'as' => 'admin.',
        'prefix' => 'admin',
        'middleware' => 'is_admin'
    ], function (){
        Route::resource('/product',Admin\ProductController::class);
        Route::delete('/product-deletemulti',[\App\Http\Controllers\Admin\ProductController::class,'deleteMulti'])->name('product.deletemuti');
        Route::get('/product-search',[\App\Http\Controllers\Admin\ProductController::class,'searchProduct'])->name('product.search');
        Route::resource('/user', Admin\UserController::class);
        Route::post('/updateus-ajax', [\App\Http\Controllers\Admin\UserController::class, 'updateAjax'])->name('user.update.ajax');
        Route::get('/task',[ App\Http\Controllers\Admin\TaskController::class , 'index'] )->name('list-task');
        Route::get('/add-task',[ App\Http\Controllers\Admin\TaskController::class , 'addTask'] )->name('addtask');
        Route::get('/edit-task/{idtask}',[ App\Http\Controllers\Admin\TaskController::class , 'editTask'] )->name('edittask');
    });
}
);

Route::get('/admin/login',[\App\Http\Controllers\Admin\Auth\LoginController::class, 'index'] )->name('admin.login');
Route::post('/admin/login',[\App\Http\Controllers\Admin\Auth\LoginController::class, 'login'])->name('admin.login');
Route::get('/admin/register-user', [\App\Http\Controllers\Admin\Auth\RegisterController::class, 'index'] )->name('admin.user.register');
Route::post('/admin/register-user', [\App\Http\Controllers\Admin\Auth\RegisterController::class, 'register'] )->name('admin.user.register');

app/Models/Product.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class Product extends Model
{
    use HasFactory;
    protected $table = "products";
    public function user(){
        return $this->belongsTo(User::class, 'is_user', 'id');
    }
    public function colors(){
//        return $this->hasMany(product_color::class, 'product_id', 'id');
//        return $this->hasManyThrough(product_color::class, Color::class,'id','id');
        return $this->belongsToMany(Color::class, product_color::class, 'product_id', 'color_id');
    }
    public function category(){
        return $this->hasOne(Product_category::class, 'product_id','id');
    }
    public static function findProduct($filterby, $keyword){
        $products = Product::with('colors');
        switch ($filterby)
        {
            case 1:
                $products = Product::with('colors')->where('name', 'LIKE', '%' . $keyword . '%');
                break;
            case 2:
                $products = Product::whereHas('colors', function ($query) use ($keyword) {
                    $query->where('name', 'LIKE', '%' . $keyword . '%');
                });
                break;
            case 3:
                $products = Product::with('colors')->where('description', 'LIKE', '%' . $keyword . '%');
                break;
        }
        $products = $products -> orderBy('id', 'desc')->paginate(10);
        return $products;
    }
    public static function createProduct($request){
        //Insertproduct
        $imageName = time().'.'.$request->image->extension();
        $request->image->move(public_path('libs/images/products'), $imageName);
        try {
            DB::beginTransaction();
            $product = new Product();
            $product -> product_code = "MSP".$product -> id;
            $product -> name = $request->nameproduct;
            $product -> price = $request->price;
            $product -> image = $imageName;
            $product -> description = $request->description;
            $product -> created_at = now();
            $product ->save();
            //Add color for product
            $product->colors()->attach($request->colors);
            //Inssert Product_Category
            $productCategory =  new Product_category();
            $productCategory -> product_id = $product->id;
            $productCategory -> category_id = $request -> category;
            $productCategory -> save();
            DB::commit();
            return true;
        } catch (\Exception $e){
            DB::rollBack();
            return false;
        }

    }
    public static function updateProduct($request, $id){
        $product = Product::find($id);
        if($request->image != ""){
            $file_path = public_path('libs/images/products/' . $product -> image);
            try {
                unlink($file_path);
            } catch (\Exception $e){

            }
            $imageName = time().'.'.$request->image->extension();
            $request->image->move(public_path('libs/images/products'), $imageName);
            $product -> image = $imageName;
        }
        try {
            DB::beginTransaction();
            $product -> product_code = "MSP".$product -> id;
            $product -> name = $request->nameproducta;
            $product -> price = $request->price;
            $product -> description = $request->description;
            $product -> created_at = Carbon::now();
            $product ->save();
            //Remove old and add new color
            $product->colors()->detach($product->colors);
            $product->colors()->attach($request->colors);
//        Update Product Category
            $productCategory =  Product_category::where('product_id',$id)->first();
            if($productCategory){
                $productCategory -> category_id = $request -> category;
                $productCategory -> save();
            } else {
                $productCategory =  new Product_category();
                $productCategory -> product_id = $id;
                $productCategory -> category_id = $request -> category;
                $productCategory -> save();
            }
            DB::commit();
            return true;
        } catch (\Exception $e){
            DB::rollBack();
            return false;
        }
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StorePostRequest;
use App\Http\Requests\UpdatePostRequest;
use App\Models\Category;
use App\Models\Color;
use App\Models\Product;
use App\Models\Product_category;
use App\Models\product_color;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use PHPUnit\Exception;


class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return |\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $searchString = trim($request->searchString);
        $filterby = $request->filterby;
        $products = Product::findProduct($filterby, $searchString);
        $data['searchString'] = $searchString;
        $data['filterby'] = $filterby;
        $data['products'] = $products;
        return view('admin.pages.product.products',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create',Product::class);
        $categories = Category::orderBy('name')->get();
        $colors = Color::orderBy('name')->get();
        $data['categories'] = $categories;
        $data['colors'] = $colors;
        return view('admin.pages.product.addproduct',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StorePostRequest $request)
    {
        $this->authorize('create',Product::class);
        $request -> validated();
        $result = Product::createProduct($request);
        if ($result == true)
            return redirect()->route('admin.product.index')->with( ['editsuccses' => $result] );
        else
            return redirect()->back()->with(['editsuccses' => $result]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function edit($id)
    {

        $product = Product::find($id);
        if($product){
            $this->authorize('update',$product);
            $categories = Category::orderBy('name')->get();
            $colors = Color::orderBy('name')->get();
            $data['colors'] = $colors;
            $data['categories'] = $categories;
            $data['product'] = $product;
            return view('admin.pages.product.editproduct',$data);
        }
        return redirect()->back()->with(['editsuccses' => -1]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, $id)
    {
        $request -> validated();
        $product = Product::find($id);
        if ($product){
            $result = Product::updateProduct($request,$id);
            if ($result == true)
                return redirect()->route('admin.product.index')->with( ['editsuccses' => $result] );
            else
                return redirect()->back()->withErrors(['Edit new Product is Fail']);
        } else {

        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response|int
     */
    public function destroy($idv, Request $request)
    {
//
        if ($request->checkdelete == 1){
            $id = $request->id;
            $product = Product::find($id);
            if($product){
                DB::beginTransaction();
                $this->authorize('delete',$product);
                $product->colors()->detach($product->colors);
                $productCategory =  Product_category::where('product_id',$id)->first();
                $productCategory -> delete();
                $product->delete();
                DB::commit();
                return 1;
            } else {
                return 0;
            }
        } else {
            $ids = $request->ids;
            Product_category::whereIn('product_id',explode(",", $ids))->delete();
            product_color::whereIn('product_id',explode(",", $ids))->delete();
            Product::whereIn('id',explode(",", $ids))->delete();
            return 1;
        }

    }
//    public function deleteMulti(Request $request){
//
//    }

}

resources/views/admin/pages/product/addproduct.blade.php
@extends('admin.layouts.main',['title' => 'Add New Product'])
@section('content')
    <div class="container">
        <div class="card card-default my-2">
            <div class="card-header">
                <h3 class="card-title">Add New Product</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form action="{{ route('admin.product.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                    <div class="error-content">
                        <ul>
                            @if ($errors -> any())
                                {{--                    {{ dd($errors) }}--}}
                                @foreach($errors->all() as $key => $value)
                                    <li class="text-danger">{{ $value }}</li>
                                @endforeach
                            @endif
                        </ul>
                    </div>
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <div class="form-group">
                        <label for="nameproduct">Name product</label>
                        <input type="text" class="form-control" name="nameproduct" id="nameproduct" placeholder="Enter Name product" value="{{ old('nameproduct') }}">
                    </div>
                    <div class="form-group ">
                        <label for="price">Price</label>
                        <input type="text" class="form-control" id="price" name="price" value="{{ old('price') }}" placeholder="Enter price">
                    </div>
                    <div class="form-group ">
                        <label for="category">Category</label>
                        <select name="category" id="category" class="form-control">
                            <option value="" disabled selected>Select category</option>
                        @foreach($categories as $key => $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group ">
                        <label for="colors">Colors</label>
                        <select name="colors[]" id="colors" class="multiple-colors form-control" multiple="multiple">
                            @foreach($colors as $key => $color)
                                <option value="{{ $color->id }}">{{ $color->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3 center upload-image">
                            <div class="btn-container">
                                <div class="imgupload">
                                    <div>
                                        <img class="imgPreview" src="{{asset('libs/images/products/imagefile.png')}}" alt="">
                                        <i class="fa fa-times removeImage"></i>
                                    </div>
                                </div>
                                <p id="namefile">Only pics allowed! (jpg,jpeg,bmp,png)</p>
                                <input type="file" class="form-control hidden" id="image" name="image" placeholder="Enter image">
                                <label type="button" id="btnup" for="image" class="btn btn-primary">Browse for your pic!</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea class="form-control" id="description" name="description" rows="4">{{ old('description') }}</textarea>
                    </div>


                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <a href="{{ route('admin.product.index') }}" class="btn btn-danger">Cancel</a>
                    <button type="submit"  class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
    @push('custom-scripts')
        <script type="text/javascript">
            createCKEditor();
            $(".multiple-colors").select2({
                maximumSelectionLength: 5
            });
        </script>
    @endpush
@endsection

resources/views/admin/pages/product/products.blade.php
@extends('admin.layouts.main',['title' => 'Products'])
@section('content')


    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Dashboard</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Product</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <div class="card">

        <div class="card-header">
            <h3 class="card-title">Bordered Table</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <div class="option-data">
                <div class="my-2 left-option">
                    <input id="checkedAll" type="checkbox">
                    @can('viewAny', \App\Models\Product::class)
                    <buttom id="" onclick="NotiDeleteMuti()" class="btn btn-danger mx-1"><i class="fas fa-trash-alt"></i> Delete</buttom>
                    @endcan
                    <a href="{{ route('admin.product.index') }}" class="btn btn-primary mx-1"><i class="fas fa-sync"></i> Refresh</a>
                    @can('create', \App\Models\Product::class)
                    <a href="{{ route('admin.product.create') }}" class="btn btn-success mx-1"><i class="fas fa-plus"></i></a>
                    @endcan
                </div>
                <div class="right-option">
                    <form action="{{ route('admin.product.index') }}" method="get">
                        <div class="input-group text-center">
                            <label class="form-control form-control-md " for="filterby">Filter by: </label>
                            <select class="form-control form-control-md" id="filterby" name="filterby" id="filterby">
                                <option value="1" {{ $filterby == 1 ? 'selected' : '' }}>Name</option>
                                <option value="2" {{ $filterby == 2 ? 'selected' : '' }}>Color</option>\
                                <option value="3" {{ $filterby == 3 ? 'selected' : '' }}>Description</option>
                            </select>
                            <input type="search" class="form-control form-control-md" onkeyup="findProduct()" value="{{ $searchString ? $searchString : '' }}" name="searchString" placeholder="Search" style="width: 30%">
                            <div class="input-group-append">
                                <button type="submit"  class="btn btn-md btn-primary">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                </div>

            </div>
            <table class="table table-bordered" id="datatable-result">
                <thead>
                <tr>
                    <th></th>
                    <th>#</th>
                    <th style="width: 10px">ID</th>
                    <th>Name Product</th>
                    <th>Price</th>
                    <th>Igame</th>
                    <th>Description</th>
                    <th>Create At</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($products as $key => $value)
                <tr id="row_{{ $value -> id  }}">
                    <td><input  type="checkbox" value="{{ $value -> id  }}" name="checkitems[]" id="check-item"></td>
                    <td>
                        @if(count($value->colors) > 0)
                        <a class="text-primary" onclick="handleDetail({{ $value -> id  }})"><i class="fas fa-plus"></i> <i class="fas fa-minus text-danger"></i></a>
                        @endif
                    </td>
                    <td>{{ $value -> id  }}</td>
                    <td>{{ $value -> name }}</td>
                    <td>{{ $value -> price }}</td>
                    <td>
                        <img src="{{ asset('libs/images/products/'.$value -> image.'')}}" alt="" style="width: 60px;">

                    </td>
                    <td>{{ $value -> description }}</td>
                    <td>{{ $value -> created_at }}</td>
                    <td class="text-center">
                        <div>
                            @can('update', $value)
                            <a title="Edit" class="text-info" href="{{ route('admin.product.edit',$value)  }}"><i class="far fa-edit"></i></a>
                            @endcan
                            @can('delete', $value)
{{--                                    <form action="{{ route('admin.product.destroy', $value) }}" method="post">--}}
{{--                                        <input type="hidden" name="_method" value="DELETE">--}}
{{--                                        @method('DELETE')--}}
{{--                                        @csrf--}}
{{--                                        <button type="submit" title="Delete" class="text-danger"><i class="fas fa-trash-alt"></i></button>--}}
{{--                                    </form>--}}
{{--                                    <a title="Delete" href="{{ route('admin.product.destroy', $value) }}" class="text-danger"><i class="fas fa-trash-alt"></i></a>--}}

                                    <a title="Delete" class="text-danger" onclick="deleteProduct({{ $value -> id }})"><i class="fas fa-trash-alt"></i></a>
                            @endcan
                        </div>
                    </td>
                </tr>
                @if(count($value->colors) > 0)
                <tr class="row-detail-hide bg-light row-detail_{{ $value -> id  }}">
                    <td colspan="3">Color: </td>
                    <td colspan="5">
                        <div class="">
                            <ol class="m-0">
                                @foreach( $value->colors as $colorr)
                                    <li class="mx-3" style="color: {{$colorr->name}}"> {{ $colorr->name }} </li>
                                @endforeach
                            </ol>

                        </div>
                    </td>

                </tr>
                @endif
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="number-pages card-footer clearfix" >
            {{ $products->links() }}
        </div>

    </div>
    @push('custom-scripts')
        <script type="text/javascript">
            $( document ).ready(function() {
                @if ( Session::get('addsuccses') == 1)
                    toastr.options.timeOut = 3000; // How long the toast will display without user interaction
                toastr.options.extendedTimeOut = 3000; // How long the toast will display after a user hovers over it
                toastr.info("Add new Product is success","Success");
                @endif

                    @if ( Session::get('editsuccses') == 1)
                    toastr.options.timeOut = 3000; // How long the toast will display without user interaction
                toastr.options.extendedTimeOut = 3000; // How long the toast will display after a user hovers over it
                toastr.info("Edit Product is success","Success");
                @endif

            });
            function handleDetail(id){
                // $(".row-detail-hide").hide();
                $("#row_"+id+ " .fa-minus").toggle();
                $("#row_"+id+ " .fa-plus").toggle();
                $(".row-detail_"+id).toggle();
            }
            function deleteProduct(id){
                Swal.fire({
                    icon: 'warning',
                    title: 'Are you sure?',
                    text: 'Delete this product!',
                    showCancelButton: true,
                    confirmButtonText: '<a style = "Color:White;" onclick="deleteRow(' + id + ')">Delete</a>',
                    cancelButtonText: 'Cancel'
                });
            }
            function deleteRow(id){
                $.ajax({
                    url: 'product/'+id,
                    method: 'DELETE',
                    data: {
                        id: id,
                        checkdelete: 1,
                        _token: '{{csrf_token()}}'
                    },
                    success: function(result) {
                        console.log(result);
                        $("#row_" + id).remove();
                        $(".row-detail_" + id).remove();
                        NotificationSuccess();
                    }
                });
            }
            function NotiDeleteMuti(){
                items = $('input[name="checkitems[]"]:checked');
                if (items.length > 0){
                    Swal.fire({
                        icon: 'warning',
                        title: 'Are you sure?',
                        text: 'Delete this products!',
                        showCancelButton: true,
                        confirmButtonText: '<a style = "Color:White;" onclick="DeleteMuti()">Delete</a>',
                        cancelButtonText: 'Cancel'
                    });
                }

            }
            function NotificationSuccess(){
                Swal.fire({
                    icon: 'success',
                    title: 'Delete Success?',
                    showCancelButton: true,
                    confirmButtonText: 'OKay',
                });
            }
            function DeleteMuti(){
                items = $('input[name="checkitems[]"]:checked');
                var allVals = [];
                for (let item of items)
                {
                    allVals.push(item.value);
                }
                join_selected_values = allVals.join(",")
                $.ajax({
                    // url: 'deletemulti',
                    url: 'product/1',
                    method: 'DELETE',
                    data: {
                        ids: join_selected_values,
                        checkdelete: 2,
                        _token: '{{csrf_token()}}'
                    },
                    success: function(result) {
                        console.log(result);
                        if (result > 0){
                            console.log(result);
                            allVals.forEach(function(e) {
                                $("#row_" + e).remove();
                                $(".row-detail_" + e).remove();
                            });
                            NotificationSuccess();
                        }


                    }
                });
            }
            function findProduct(){

                // $("#datatable-result").DataTable(
                //     {
                //
                //     }
                // );
            }
        </script>
    @endpush
@endsection